details:
  namespace: student4-bookinfo-prd
  image: ghcr.io/tian-np/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.opsta.net
  path: "/student4/details(/|$)(.*)"
  serviceType: ClusterIP
