details:
  namespace: student4-bookinfo-uat
  image: ghcr.io/tian-np/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student4/details(/|$)(.*)"
  serviceType: ClusterIP

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2

